name: Wheels CI

on:
  workflow_dispatch:
    inputs:
      pymol_version:
        description: "PyMOL version"
        required: false
        default: "dev"
        type: string
      publish_to_pypi:
        description: "Publish wheels to PyPI"
        required: false
        default: false
        type: boolean

jobs:
  publish:
    name: Publish Wheels to PyPI
    needs:
      # - detect-version
      # - build-linux
      # - build-windows
      # - build-macos
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    # if: inputs.publish_to_pypi

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Combine all wheels
        run: |
          mkdir final_dist
          find dist -name "*.whl" -exec cp {} final_dist/ \;
          echo "Wheels to publish:"
          ls -la final_dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: final_dist

  publish-to-testpypi:
    name: Publish Wheels to TestPyPI

    permissions:
      id-token: write

    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/<package-name>

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Publish distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
