name: publish

on:
  workflow_dispatch:
    inputs:
      build_run_id:
        description: "Build workflow run ID (optional - will use latest successful if not provided)"
        required: false
        type: string
      publish_to_pypi:
        description: "Publish wheels to PyPI"
        required: false
        default: false
        type: boolean

jobs:
  publish:
    name: Publish Wheels to PyPI
    permissions:
      id-token: write
      actions: read
      contents: read
    runs-on: ubuntu-latest
    if: inputs.publish_to_pypi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find latest successful build run
        id: find-build
        uses: ./.github/actions/find-build-run
        with:
          build_run_id: ${{ inputs.build_run_id }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts from build workflow
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ steps.find-build.outputs.run-id }}
          path: dist

      - name: Combine all wheels
        run: |
          mkdir final_dist
          find dist -name "*.whl" -exec cp {} final_dist/ \;
          echo "Wheels to publish:"
          ls -la final_dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: final_dist

  publish-to-testpypi:
    name: Publish Wheels to TestPyPI

    permissions:
      id-token: write
      actions: read
      contents: read

    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/pymol-open-source

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find latest successful build run
        id: find-build
        uses: ./.github/actions/find-build-run
        with:
          build_run_id: ${{ inputs.build_run_id }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts from build workflow
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ steps.find-build.outputs.run-id }}
          path: dist

      - name: Combine all wheels
        run: |
          mkdir final_dist
          find dist -name "*.whl" -exec cp {} final_dist/ \;
          echo "Wheels to publish:"
          ls -la final_dist/

      - name: Publish distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: final_dist
