name: release

on:
  # push:
  # pull_request:
  workflow_dispatch:
    inputs:
      pymol_version:
        description: "PyMOL version"
        required: false
        default: "dev"
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PYMOL_VERSION: ${{ inputs.pymol_version || 'dev' }}

jobs:
  github-release:
    name: Create GitHub Release
    needs:
      - detect-version
      - build-linux
      # - build-windows
      - build-macos
    runs-on: ubuntu-latest
    # if: github.event_name == 'workflow_dispatch'
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release assets
        run: |
          mkdir release-assets
          find artifacts -name "*.whl" -exec cp {} release-assets/ \;
          echo "Release assets:"
          ls -la release-assets/

      - name: Create GitHub release with wheels
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            let pymolVersion = '${{ needs.detect-version.outputs.pymol_version }}';
            if (pymolVersion === '' || pymolVersion === 'dev') {
              pymolVersion = 'latest';
            } else if (!pymolVersion || !/^[A-Za-z0-9._\-]+$/.test(pymolVersion)) {
              throw new Error(`Invalid pymolVersion: "${pymolVersion}". Aborting release.`);
            }
            const tagName = `pymol-open-source-${pymolVersion}`;
            const releaseName = `PyMOL ${pymolVersion} Wheels`;

            try {
              // Create the release
              const release = await github.rest.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: tagName,
                name: releaseName,
                body: `PyMOL ${pymolVersion} wheels built and ready for download!

            **PyMOL Version:** ${pymolVersion}
            **Source:** https://github.com/schrodinger/pymol-open-source/releases/tag/${pymolVersion}

            ## Installation

            Download the wheel file for your platform and install with:
            \`\`\`bash
            pip install pymol_open_source-${pymolVersion}-*.whl
            \`\`\`

            Or install from PyPI:
            \`\`\`bash
            pip install pymol-open-source
            \`\`\`

            ## What's included

            - Linux wheels (x86_64)
            - Windows wheels (x86_64)
            - macOS wheels (x86_64, arm64)
            - Python 3.9, 3.10, 3.11, 3.12, 3.13 support

            Built automatically from PyMOL upstream release using official build instructions.`,
                draft: false,
                prerelease: false
              });

              console.log('✅ GitHub release created:', release.data.html_url);

              // Upload wheel files as release assets
              const assetsDir = './release-assets';
              const files = fs.readdirSync(assetsDir);

              for (const file of files) {
                if (file.endsWith('.whl')) {
                  const filePath = path.join(assetsDir, file);
                  const fileContent = fs.readFileSync(filePath);

                  await github.rest.repos.uploadReleaseAsset({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    release_id: release.data.id,
                    name: file,
                    data: fileContent,
                  });

                  console.log(`✅ Uploaded ${file} to release`);
                }
              }

            } catch (error) {
              if (error.message.includes('already_exists')) {
                console.log('⚠️ Release already exists, skipping creation');
              } else {
                console.error('❌ Failed to create GitHub release:', error.message);
                throw error;
              }
            }
